services:
  mediatree:
    build: .
    container_name: mediatree
    ports:
      - "27580:27580" 
    volumes:
      - /Volumes/o2/test/bgm:/media/bgm:ro                                                 
      - /Volumes/o2/test/movie:/media/movie:ro                                                 
      - /Volumes/o2/test/jav:/media/jav:ro                                                                                        
      - /Volumes/STU/Code/mediatree/data:/app/data 
    env_file:
      - .env
    environment:
      - PORT=27580
    restart: unless-stopped
