import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
WINDOWS_PROJECT = ROOT / "windows" / "MediaTree.Windows" / "MediaTree.Windows.csproj"
WINDOWS_APP = ROOT / "windows" / "MediaTree.Windows"
WINDOWS_MANIFEST = ROOT / "windows" / "MediaTree.Windows" / "Package.appxmanifest"
WINDOWS_WORKFLOW = ROOT / ".github" / "workflows" / "windows-release.yml"
WINDOWS_BUILD_SCRIPT = ROOT / "packaging" / "windows" / "build-windows.ps1"
WINDOWS_PREPARE_MPV_SCRIPT = ROOT / "packaging" / "windows" / "prepare-mpv.ps1"
PYINSTALLER_SPEC = ROOT / "packaging" / "windows" / "mediatree-server.spec"


def read_windows_source(*parts):
    return (WINDOWS_APP.joinpath(*parts)).read_text(encoding="utf-8")


def read_mediatree_api_client_source():
    return "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((WINDOWS_APP / "Services").glob("MediaTreeApiClient*.cs"))
    )


def assert_windows_platform_source(test_case, file_name):
    source = read_windows_source("Platform", file_name)
    test_case.assertIn("namespace MediaTree.Windows.Platform;", source)
    test_case.assertFalse((WINDOWS_APP / "Services" / file_name).exists())
    return source


class WindowsPackagingTest(unittest.TestCase):
    def test_winui_project_bundles_backend_server_and_native_runtime(self):
        project = WINDOWS_PROJECT.read_text(encoding="utf-8")

        self.assertIn("<UseWinUI>true</UseWinUI>", project)
        self.assertIn("<WindowsPackageType>None</WindowsPackageType>", project)
        self.assertIn("<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>", project)
        self.assertIn("Microsoft.WindowsAppSDK", project)
        self.assertIn("CommunityToolkit.Mvvm", project)
        self.assertNotIn("Microsoft.Web.WebView2", project)
        self.assertIn("server\\**\\*", project)
        self.assertIn("IncludeBundledMpvFiles", project)
        self.assertIn('<None Include="mpv\\**\\*" Exclude="mpv\\mpv.exe">', project)
        self.assertIn("<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>", project)
        self.assertIn("Package.appxmanifest", project)
        self.assertIn("<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>", project)
        self.assertIn("PrepareBundledMpv", project)
        self.assertIn("packaging\\windows\\prepare-mpv.ps1", project)

    def test_windows_project_prepare_mpv_target_copies_libmpv_before_publish(self):
        project = WINDOWS_PROJECT.read_text(encoding="utf-8")
        script = WINDOWS_PREPARE_MPV_SCRIPT.read_text(encoding="utf-8")

        self.assertIn('BeforeTargets="AssignTargetPaths"', project)
        self.assertIn("PowershellRuntime", project)
        self.assertIn("powershell", project)
        self.assertIn("-NoProfile -ExecutionPolicy Bypass -File", project)
        self.assertIn("prepare-mpv.ps1", project)
        self.assertIn("-Destination", project)
        self.assertIn("$(MSBuildProjectDirectory)\\mpv", project)
        self.assertIn("SkipPrepareBundledMpv", project)
        self.assertIn("'$(OS)' == 'Windows_NT'", project)
        self.assertIn("mpv-2.dll", script)
        self.assertIn("libmpv-2.dll", script)
        self.assertIn("MpvArchiveUrl", script)
        self.assertIn("LibMpvArchiveUrl", script)
        self.assertIn("function Resolve-7ZipTool", script)
        self.assertIn("7zr.exe", script)
        self.assertIn("$SevenZipUrl", script)
        self.assertIn("py7zr", script)
        self.assertIn("SkipMpvDownload", script)
        self.assertIn("Bundled mpv-2.dll was not copied", script)
        self.assertIn("Remove-Item (Join-Path $Destination \"mpv.exe\") -Force", script)
        self.assertIn("Copy-Item (Join-Path $mpvDll.Directory.FullName \"*\") $Destination -Recurse -Force", script)

    def test_msix_manifest_declares_full_trust_desktop_app(self):
        manifest = WINDOWS_MANIFEST.read_text(encoding="utf-8")

        self.assertIn('Name="ZASENJC.MediaTree"', manifest)
        self.assertIn('Name="Windows.Desktop"', manifest)
        self.assertIn('Name="runFullTrust"', manifest)
        self.assertIn('Square150x150Logo="Assets\\Square150x150Logo.png"', manifest)

    def test_pyinstaller_spec_preserves_base_app_for_hot_updates(self):
        spec = PYINSTALLER_SPEC.read_text(encoding="utf-8")

        self.assertIn('"backend" / "app"', spec)
        self.assertIn('"base/app"', spec)
        self.assertIn('"frontend" / "dist"', spec)
        self.assertIn('"base/frontend/dist"', spec)
        self.assertIn('"backend" / "app" / "windows_entry.py"', spec)
        self.assertIn('name="mediatree-server"', spec)
        self.assertIn("collect_submodules", spec)
        self.assertIn("SPECPATH", spec)
        self.assertNotIn("__file__", spec)
        self.assertNotIn("ROOT = Path.cwd()", spec)
        self.assertNotIn('"app.main"', spec)

    def test_windows_build_script_runs_validation_before_packaging(self):
        script = WINDOWS_BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertLess(
            script.index("python -m pip install -r backend/requirements.txt"),
            script.index('python -m unittest discover -s tests -p "test_*.py"'),
        )
        self.assertIn("function Invoke-Native", script)
        self.assertIn("$FilePath = [string]$args[0]", script)
        self.assertNotIn("ValueFromRemainingArguments", script)
        self.assertIn("throw \"$FilePath failed with exit code $LASTEXITCODE\"", script)
        self.assertIn('python -m unittest discover -s tests -p "test_*.py"', script)
        self.assertIn("python -m compileall -q backend/app", script)
        self.assertIn("npm.cmd run build", script)
        self.assertIn("pyinstaller --noconfirm", script)
        self.assertIn('$ServerDist = Join-Path $Root "dist/windows/server"', script)
        self.assertIn('$ServerWork = Join-Path $Root "build/windows/mediatree-server"', script)
        self.assertIn("Remove-Item $ServerSource -Recurse -Force", script)
        self.assertIn("Remove-Item $ServerWork -Recurse -Force", script)
        self.assertIn("packaging/windows/prepare-mpv.ps1", script)
        self.assertIn("if ($SkipMpvDownload)", script)
        self.assertIn('$prepareArgs += "-SkipMpvDownload"', script)
        self.assertIn('$prepareArgs += @("-MpvArchivePath", $MpvArchivePath)', script)
        self.assertIn('$prepareArgs += @("-LibMpvArchivePath", $LibMpvArchivePath)', script)
        self.assertIn("/p:SkipPrepareBundledMpv=true", script)
        self.assertNotIn("Bundled mpv.exe was copied", script)
        self.assertIn("mpv-2.dll", script)
        self.assertIn("$MsixVersion", script)
        self.assertIn("docs/assets/logo.png", script)
        self.assertIn("$OriginalManifest", script)
        self.assertIn("function Resolve-WindowsKitTool", script)
        self.assertIn("function Resolve-MSBuild", script)
        self.assertIn("function Resolve-PowershellTool", script)
        self.assertIn("function New-ExpandedAppxManifest", script)
        self.assertIn("function New-AppInstallerFile", script)
        self.assertIn("function New-TestSigningCertificate", script)
        self.assertIn("/t:Publish", script)
        self.assertIn("WindowsAppSDKSelfContained=true", script)
        self.assertIn("WindowsPackageType=None", script)
        self.assertIn("SelfContained=true", script)
        self.assertIn("PublishSingleFile=false", script)
        self.assertIn("makeappx.exe", script)
        self.assertIn("signtool.exe", script)
        self.assertIn("MediaTree-Windows-$Version.msix", script)
        self.assertIn("MediaTree-Windows-$Version.appinstaller", script)
        self.assertIn("MediaTree-Windows-$Version.cer", script)
        self.assertIn("MediaTree-Windows-$Version-portable.zip", script)
        self.assertIn('".zip"', script)
        self.assertIn('".cer"', script)
        self.assertIn("Windows.FullTrustApplication", script)
        self.assertIn("ProcessorArchitecture", script)
        self.assertIn("MSIX package was not generated", script)
        self.assertIn('if (Test-Path (Join-Path $ShellOutput "mpv/mpv.exe"))', script)
        self.assertIn("must not include bundled mpv.exe", script)
        self.assertLess(
            script.index('if (Test-Path (Join-Path $ShellOutput "mpv/mpv.exe"))'),
            script.index('if (-not (Test-Path (Join-Path $ShellOutput "mpv/mpv-2.dll")))'),
        )
        self.assertIn("App installer file was not generated", script)
        self.assertIn("Portable package was not generated", script)
        self.assertNotIn("GenerateAppxPackageOnBuild=true", script)

    def test_windows_shell_uses_native_pages_api_client_and_libmpv(self):
        api_client = read_mediatree_api_client_source()
        auth_service = read_windows_source("Services", "AuthSessionService.cs")
        backend_service = read_windows_source("Services", "BackendProcessService.cs")
        app_services = read_windows_source("Services", "AppServices.cs")
        media_tree_services = read_windows_source("Providers", "MediaTree", "MediaTreeServices.cs")
        media_tree_provider = read_windows_source("Providers", "MediaTree", "IMediaTreeProvider.cs")
        local_media_tree_provider = read_windows_source("Providers", "MediaTree", "LocalMediaTreeProvider.cs")
        app_paths = assert_windows_platform_source(self, "AppPaths.cs")
        backend_access_store = assert_windows_platform_source(self, "BackendAccessSettingsStore.cs")
        port_allocator = assert_windows_platform_source(self, "PortAllocator.cs")
        shell_logger = assert_windows_platform_source(self, "ShellLogger.cs")
        ui_preference_store = assert_windows_platform_source(self, "UiPreferenceStore.cs")
        window_modal_dialog = assert_windows_platform_source(self, "WindowModalDialog.cs")
        mpv_native = read_windows_source("Interop", "MpvNative.cs")
        mpv_control = read_windows_source("Controls", "MpvPlayerControl.xaml.cs")
        app = read_windows_source("App.xaml.cs")
        main_window = read_windows_source("MainWindow.xaml.cs")
        main_window_xaml = read_windows_source("MainWindow.xaml")
        fluent_theme = read_windows_source("Styles", "FluentTheme.cs")
        shell_page = read_windows_source("Views", "ShellPage.xaml")
        shell_page_cs = read_windows_source("Views", "ShellPage.xaml.cs")
        setup_required_page = read_windows_source("Views", "SetupRequiredPage.xaml.cs")
        setup_page = read_windows_source("Views", "SetupPage.xaml")
        setup_page_cs = read_windows_source("Views", "SetupPage.xaml.cs")
        library_page = read_windows_source("Views", "LibraryPage.xaml")
        library_page_cs = read_windows_source("Views", "LibraryPage.xaml.cs")
        folder_page = read_windows_source("Views", "FolderPage.xaml")
        folder_page_cs = read_windows_source("Views", "FolderPage.xaml.cs")
        folder_card_item = read_windows_source("ViewModels", "FolderCardItem.cs")
        browse_page_cs = read_windows_source("Views", "BrowsePage.xaml.cs")
        favorites_page_cs = read_windows_source("Views", "FavoritesPage.xaml.cs")
        settings_page_cs = read_windows_source("Views", "SettingsPage.xaml.cs")
        movie_detail_page_cs = read_windows_source("Views", "MovieDetailPage.xaml.cs")
        navigation_parameters = read_windows_source("Models", "NavigationParameters.cs")
        movie_dtos = read_windows_source("Models", "MovieDtos.cs")
        movie_card_item = read_windows_source("ViewModels", "MovieCardItem.cs")
        player_page = read_windows_source("Views", "PlayerPage.xaml")
        player_page_cs = read_windows_source("Views", "PlayerPage.xaml.cs")

        self.assertNotIn("WebView2", main_window_xaml)
        self.assertNotIn("Microsoft.Web.WebView2", main_window)
        self.assertNotIn("CoreWebView2", main_window)
        self.assertNotIn("AddScriptToExecuteOnDocumentCreatedAsync", main_window)
        self.assertIn("AuthSessionService", main_window)
        self.assertIn("MediaTreeApiClient", main_window)
        self.assertIn("new MediaTreeServices", main_window)
        self.assertIn("new LocalMediaTreeProvider(mediaTreeServices)", main_window)
        self.assertIn("ShellPage", main_window)
        self.assertIn("public sealed class MediaTreeServices", media_tree_services)
        self.assertIn("MediaTreeApiClient Api", media_tree_services)
        self.assertIn("AuthSessionService Auth", media_tree_services)
        self.assertIn("LibraryService Library", media_tree_services)
        self.assertIn("MovieService Movie", media_tree_services)
        self.assertIn("UpdateService Updates", media_tree_services)
        self.assertIn("PlaybackProgressService PlaybackProgress", media_tree_services)
        self.assertIn("MediaTreeServices Services { get; }", media_tree_provider)
        self.assertIn("public LocalMediaTreeProvider(MediaTreeServices services)", local_media_tree_provider)
        self.assertIn("public MediaTreeServices Services { get; }", local_media_tree_provider)
        self.assertIn("public static MediaTreeServices MediaTree", app_services)
        self.assertIn("MediaTree = provider.Services", app_services)
        self.assertIn("Api = MediaTree.Api", app_services)
        self.assertIn("BackendAccessSettingsStore.Load", backend_service)
        self.assertIn("--host {_accessSettings.BindHost}", backend_service)
        self.assertIn("WindowsStateDirectory", app_paths)
        self.assertIn("GetFreeLoopbackPort", port_allocator)
        self.assertIn("LogFile", shell_logger)
        self.assertIn("public WindowModalDialog(", window_modal_dialog)
        self.assertIn("0.0.0.0", backend_access_store)
        self.assertIn("DefaultRemotePort = 27581", backend_access_store)
        self.assertIn("args.Handled = true", app)
        self.assertIn("ShowAndBringToFront()", main_window)
        self.assertIn("WindowNative.GetWindowHandle(this)", main_window)
        self.assertIn("ShowStartupFailure", main_window)
        self.assertIn("CenteredCard(stack", main_window)
        self.assertIn('AutomationProperties.SetAutomationId(startupTitle, "StartupTitle")', main_window)
        self.assertIn("HorizontalAlignment.Stretch", main_window)
        self.assertIn("MaxWidth = 480", main_window)
        self.assertIn("CenteredCard", fluent_theme)
        self.assertIn("HorizontalAlignment = HorizontalAlignment.Center", fluent_theme)
        self.assertIn("VerticalAlignment = VerticalAlignment.Center", fluent_theme)
        self.assertIn("ShellNavigation", shell_page + shell_page_cs)
        self.assertIn("ContentFrame", shell_page + shell_page_cs)
        self.assertIn("AutomationProperties.AutomationId", shell_page + shell_page_cs)
        self.assertIn("NavHome", shell_page + shell_page_cs)
        self.assertIn("NavBrowse", shell_page + shell_page_cs)
        self.assertIn("NavFavorites", shell_page + shell_page_cs)
        self.assertNotIn("NavLibrary", shell_page_cs)
        self.assertNotIn("NavRecent", shell_page_cs)
        self.assertNotIn('CreateNavigationButton("媒体库"', shell_page_cs)
        self.assertNotIn('CreateNavigationButton("最近观看"', shell_page_cs)
        self.assertIn("SetupRequiredPage", shell_page_cs)
        self.assertIn("SetupRequiredAddFolder", setup_required_page)
        self.assertIn("FolderPicker", setup_page_cs)
        self.assertIn("InitializeWithWindow.Initialize(picker", setup_page_cs)
        self.assertIn("Folder picker failed.", setup_page_cs)
        self.assertIn("AddLibraryAsync", setup_page + setup_page_cs)
        self.assertIn("SetupScraperTmdbMovie", setup_page_cs)
        self.assertIn("SetupScraperTmdbTv", setup_page_cs)
        self.assertIn("SetupScraperJavdatabase", setup_page_cs)
        self.assertIn("SetupTmdbAccessToken", setup_page_cs)
        self.assertIn("SetupLibraryPassword", setup_page_cs)
        self.assertNotIn('"tmdb", "SetupScraperTmdb"', setup_page_cs)
        self.assertIn("SaveTmdbConfigAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("NormalizeScraper", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("MoviesGrid", library_page + library_page_cs)
        self.assertIn("Failed to load native library movies.", library_page_cs)
        self.assertIn("Failed to start native library scan.", library_page_cs)
        self.assertIn("StartLibraryScanInBackgroundAsync", library_page_cs)
        self.assertIn("_ = StartLibraryScanInBackgroundAsync(mediaRoot)", library_page_cs)
        self.assertIn("LibraryScanProgressTrack", library_page_cs)
        self.assertIn("LibraryScanProgressFill", library_page_cs)
        self.assertIn("ScanProgressWidth = 220", library_page_cs)
        self.assertIn("ScanProgressRowHeight = 20", library_page_cs)
        self.assertIn("new RowDefinition { Height = new GridLength(ScanProgressRowHeight) }", library_page_cs)
        self.assertIn("Width = ScanProgressWidth", library_page_cs)
        self.assertIn("HorizontalAlignment = HorizontalAlignment.Right", library_page_cs)
        self.assertIn("UpdateScanProgressFill(status.Done, status.Total)", library_page_cs)
        self.assertIn("var ratio = total > 0 ? Math.Clamp(done / (double)total, 0, 1) : 0", library_page_cs)
        self.assertNotIn('ShowInfo("已开始整理', library_page_cs)
        self.assertIn("_suppressLibrarySelectionChanged", library_page_cs)
        self.assertIn("_movieLoadGeneration", library_page_cs)
        self.assertIn("CreateLibraryItem", library_page_cs)
        self.assertIn("Tag = root", library_page_cs)
        self.assertIn("Failed to change native library selection.", library_page_cs)
        self.assertIn("/folders", api_client)
        self.assertIn("FolderGrid", library_page_cs)
        self.assertIn("CreateFolderCard", library_page_cs)
        self.assertIn("FolderCardItem", library_page_cs)
        self.assertIn("UiPreferenceStore.Load", library_page_cs)
        self.assertIn("_hideHomeTitleText", library_page_cs)
        self.assertIn("_showSourceName", library_page_cs)
        self.assertIn("item.SourceName", library_page_cs)
        self.assertIn("SourceName => Folder.Name", folder_card_item)
        self.assertIn("FolderNavigationParameter", navigation_parameters)
        self.assertIn("NavigateToFolder", shell_page_cs)
        self.assertIn("_contentFrame.Navigate(typeof(FolderPage), new FolderNavigationParameter", shell_page_cs)
        self.assertIn("_contentFrame.Navigate(typeof(MovieDetailPage), new MovieNavigationParameter(movieId))", shell_page_cs)
        self.assertIn("ShellPage.Current?.NavigateToPlayer(_movieId)", movie_detail_page_cs)
        self.assertIn("ShellPage.Current?.NavigateToFolder(item.Path, _activeMediaRoot, item.Title)", library_page_cs)
        self.assertNotIn("LoadMoviesAsync(item.Path)", library_page_cs)
        self.assertIn("FolderPage", folder_page + folder_page_cs)
        self.assertIn("FolderSeasonTabs", folder_page_cs)
        self.assertIn("FolderMoviesGrid", folder_page_cs)
        self.assertIn("onClick: () => ShellPage.Current?.NavigateToPlayer(movie.Id)", folder_page_cs)
        self.assertIn("Action? onClick = null", browse_page_cs)
        self.assertIn("card.Click += (_, _) => onClick?.Invoke();", browse_page_cs)
        self.assertIn("onClick ??= () => ShellPage.Current?.NavigateToMovie(item.Id);", browse_page_cs)
        self.assertIn("GetMoviesAsync(_mediaRoot, _folderPath", folder_page_cs)
        self.assertIn("BuildSeasonTabs", folder_page_cs)
        self.assertIn("IsInSeason", folder_page_cs)
        self.assertIn("folder_levels", movie_dtos)
        self.assertIn("tmdb_type", movie_dtos)
        self.assertIn("tmdb_season", movie_dtos)
        self.assertIn("tmdb_episode", movie_dtos)
        self.assertIn("episode_number", movie_dtos)
        self.assertIn("episode_title", movie_dtos)
        self.assertIn("episode_still", movie_dtos)
        self.assertIn("LibraryLoadingText", library_page_cs)
        self.assertIn("SetLoading", library_page_cs)
        self.assertNotIn("ProgressRing", library_page_cs)
        self.assertIn("LibraryScanInfoText", library_page_cs)
        self.assertNotIn("new InfoBar", library_page_cs)
        self.assertIn("BrowsePage", shell_page_cs)
        self.assertIn("BrowseFoldersList", browse_page_cs)
        self.assertIn("BrowseMoviesGrid", browse_page_cs)
        self.assertIn("BrowseSearchBox", browse_page_cs)
        self.assertIn("BrowseSort", browse_page_cs)
        self.assertIn("GetMoviesAsync(_activeMediaRoot, _activeFolderPath", browse_page_cs)
        self.assertIn("FavoritesPage", shell_page_cs)
        self.assertIn("FavoritesMoviesGrid", favorites_page_cs)
        self.assertIn("FavoritesSort", favorites_page_cs)
        self.assertIn("GetFavoritesAsync", favorites_page_cs)
        self.assertIn("RemoveTagAsync", favorites_page_cs)
        self.assertIn("SettingsUpdateStatusText", settings_page_cs)
        self.assertIn("ShowUpdateStatus", settings_page_cs)
        self.assertIn("Failed to check native Windows updates.", settings_page_cs)
        self.assertIn("SettingsUiPrefsCard", settings_page_cs)
        self.assertIn("SettingsLibraryCard", settings_page_cs)
        self.assertIn("SettingsScraperCard", settings_page_cs)
        self.assertIn("SettingsBackupCard", settings_page_cs)
        self.assertIn("SettingsUpdateCard", settings_page_cs)
        self.assertIn("SettingsRemoteBackendCard", settings_page_cs)
        self.assertIn("SettingsAllowRemoteBackend", settings_page_cs)
        self.assertIn("SettingsRemoteBackendUrl", settings_page_cs)
        self.assertIn("SettingsRemoteLoginUsername", settings_page_cs)
        self.assertIn("SettingsRemoteLoginPassword", settings_page_cs)
        self.assertIn("SettingsRemoteAccessContent", settings_page_cs)
        self.assertIn("remoteAccessContent.Children.Add(remoteBackendPortBox)", settings_page_cs)
        self.assertIn("remoteAccessContent.Children.Add(remoteLoginUsernameBox)", settings_page_cs)
        self.assertIn("remoteAccessContent.Children.Add(remoteLoginPasswordBox)", settings_page_cs)
        self.assertNotIn("remoteStack.Children.Add(TwoColumnRow(remoteLoginUsernameBox, remoteLoginPasswordBox))", settings_page_cs)
        self.assertIn("SaveRemoteAccessButtonText", settings_page_cs)
        self.assertNotIn("SettingsAuthCard", settings_page_cs)
        self.assertNotIn("SettingsSetMobileLogin", settings_page_cs)
        self.assertIn("OnSaveRemoteBackendClicked", settings_page_cs)
        self.assertIn("_settingsCards", settings_page_cs)
        self.assertIn("RenderSettingsCardColumns", settings_page_cs)
        self.assertIn("new StackPanel { Spacing = 20", settings_page_cs)
        self.assertIn("settingsGrid.Children.Add(columnStack)", settings_page_cs)
        self.assertIn("columnStack.Children.Add(child)", settings_page_cs)
        self.assertIn("child.Height = double.NaN", settings_page_cs)
        self.assertNotIn("settingsGrid.RowDefinitions.Add", settings_page_cs)
        self.assertNotIn("Grid.SetRow(child, index % rowsNeeded)", settings_page_cs)
        self.assertIn("SettingsSaveGlobal", settings_page_cs)
        self.assertIn("SettingsHideHomeTitleText", settings_page_cs)
        self.assertIn("SettingsShowSourceName", settings_page_cs)
        self.assertIn("uiPrefsStack.Children.Add(hideHomeTitleTextBox)", settings_page_cs)
        self.assertIn("uiPrefsStack.Children.Add(showSourceNameBox)", settings_page_cs)
        self.assertNotIn("FluentTheme.PreferenceRow", settings_page_cs)
        self.assertIn("OnUiPreferenceChanged", settings_page_cs)
        self.assertIn("UiPreferenceStore.Save", settings_page_cs)
        self.assertIn("hideHomeTitleText", ui_preference_store)
        self.assertIn("showSourceName", ui_preference_store)
        self.assertIn("SettingsTmdbApiKey", settings_page_cs)
        self.assertIn("SettingsScraperContent", settings_page_cs)
        self.assertIn("scraperContent.Children.Add(tmdbApiKeyBox)", settings_page_cs)
        self.assertIn("scraperContent.Children.Add(tmdbTokenBox)", settings_page_cs)
        self.assertIn("scraperContent.Children.Add(ScraperDescriptionGrid())", settings_page_cs)
        self.assertNotIn("SettingsChangePassword", settings_page_cs)
        self.assertIn("RemoteLoginUsernameHeader", settings_page_cs)
        self.assertIn("SettingsBackupCore", settings_page_cs)
        self.assertIn("SettingsBackupFull", settings_page_cs)
        self.assertIn("SettingsRestoreBackup", settings_page_cs)
        self.assertIn("SaveBackupAsync", settings_page_cs)
        self.assertIn("DownloadBackupAsync", api_client)
        self.assertIn("SettingsLibrarySettingsList", settings_page_cs)
        self.assertIn("SettingsLibraryStatusText", settings_page_cs)
        self.assertIn("SettingsTmdbAccessToken", settings_page_cs)
        self.assertNotIn("SettingsSaveTmdbToken", settings_page_cs)
        self.assertIn("SettingsTmdbTokenStatusText", settings_page_cs)
        self.assertIn("LoadTmdbConfigAsync", settings_page_cs)
        self.assertIn("SaveGlobalConfigAsync", settings_page_cs)
        self.assertIn("SettingsSaveLibrary_", settings_page_cs)
        self.assertIn("SettingsLibraryScraper_", settings_page_cs)
        self.assertIn("正在保存刮削器设置并重新扫描", settings_page_cs)
        self.assertIn("GetScanStatusAsync", settings_page_cs)
        self.assertIn("GetScanLogAsync", settings_page_cs)
        self.assertIn("StartLibraryScanInBackgroundAsync", settings_page_cs)
        self.assertIn("AddLibraryFromSettingsAsync", settings_page_cs)
        self.assertIn("AddLibraryRootAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("ScraperOptions", settings_page_cs)
        self.assertIn('new("tmdb_movie", "TMDB 电影", "适合电影库；tmdbid 调用 /movie 精确刮削", true)', settings_page_cs)
        self.assertIn('new("tmdb_tv", "TMDB 剧集/番剧", "适合剧集、番剧、电视剧库；tmdbid 调用 /tv 精确刮削", true)', settings_page_cs)
        self.assertIn('new("bangumi", "Bangumi", "适合番剧、动画、二次元条目，数据可能不全", false)', settings_page_cs)
        self.assertIn('new("javdatabase", "Javdatabase", "适合 JAV 番号识别和刮削", false)', settings_page_cs)
        self.assertIn('new("auto", "自动", "自动判断刮削源，但可能效果不好", true)', settings_page_cs)
        self.assertIn('new("none", "不刮削", "只扫描本地文件，不联网刮削元数据", false)', settings_page_cs)
        self.assertNotIn("new InfoBar", settings_page_cs)
        self.assertIn("GetLibrarySettingsAsync", api_client)
        self.assertIn('GetAsync<List<LibrarySettingDto>>("/library-settings"', api_client)
        self.assertIn("SaveLibrarySettingAsync", api_client)
        self.assertIn("SaveTmdbConfigAsync", api_client)
        self.assertIn("SaveGlobalConfigAsync", api_client)
        self.assertIn("ChangePasswordAsync", api_client)
        self.assertIn("ChangeStoredSessionCredentialsAsync", settings_page_cs)
        self.assertIn("_remoteLoginUsernameBox.Text.Trim()", settings_page_cs)
        self.assertIn("_remoteLoginPasswordBox.Password", settings_page_cs)
        self.assertIn("GetFavoritesAsync", api_client)
        self.assertIn("RemoveTagAsync", api_client)
        self.assertIn("ClearLibraryAsync", api_client)
        self.assertIn("RestoreBackupAsync", api_client)
        self.assertIn("GetUpdateStatusAsync", api_client)
        self.assertIn("PerformUpdateAsync", api_client)
        self.assertIn("RollbackUpdateAsync", api_client)
        self.assertIn("GetChangelogAsync", api_client)
        self.assertIn("SettingsPerformUpdate_", settings_page_cs)
        self.assertIn("SettingsRollbackUpdate_", settings_page_cs)
        self.assertIn("SettingsUpdateChangelog_", settings_page_cs)
        self.assertIn("SettingsDownloadFullUpdate_", settings_page_cs)
        self.assertIn("RestartBackendAfterAppPackageUpdateAsync", settings_page_cs)
        self.assertIn("CheckUpdatesOnLoadAsync", settings_page_cs)
        self.assertIn("Timeout = TimeSpan.FromMinutes(10)", api_client)
        update_dtos = (ROOT / "windows" / "MediaTree.Windows" / "Models" / "UpdateDtos.cs").read_text(encoding="utf-8")
        self.assertIn("windows-full-required", update_dtos)
        self.assertIn("windows_download_url", update_dtos)
        self.assertNotIn("requires_image_update", update_dtos)
        self.assertIn("tmdb_access_token", api_client)
        self.assertIn("tmdb_api_key", api_client)
        self.assertIn("TmdbAccessToken", (ROOT / "windows" / "MediaTree.Windows" / "Models" / "LibraryDtos.cs").read_text(encoding="utf-8"))
        self.assertIn("GetLibrarySettingsAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("SaveLibrarySettingAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("Failed to load native movie detail.", movie_detail_page_cs)
        self.assertIn("DetailStatusText", movie_detail_page_cs)
        self.assertIn("ImageFailed", movie_detail_page_cs)
        self.assertIn("ShowDetailError", movie_detail_page_cs)
        self.assertNotIn("ProgressBar", movie_detail_page_cs)
        self.assertIn("PlayerHost", player_page + player_page_cs)
        self.assertIn("PlayerStatusText", player_page_cs)
        self.assertIn("PlayerPlayPause", player_page_cs)
        self.assertIn("PlayerProgressSlider", player_page_cs)
        self.assertIn("PlayerTime", player_page_cs)
        self.assertIn("PlayerResumePrompt", player_page_cs)
        self.assertIn("_resumePromptTimer = new() { Interval = TimeSpan.FromSeconds(5) }", player_page_cs)
        self.assertIn("_resumePromptTimer.Tick += OnResumePromptTimerTick", player_page_cs)
        self.assertIn("ScheduleResumePromptAutoHide", player_page_cs)
        self.assertIn("OnResumePromptTimerTick", player_page_cs)
        self.assertIn("BorderThickness = new Thickness(0)", player_page_cs)
        self.assertIn("Background = new SolidColorBrush(Microsoft.UI.Colors.Transparent)", player_page_cs)
        self.assertIn("_chromeTimer = new() { Interval = TimeSpan.FromSeconds(5) }", player_page_cs)
        self.assertIn("PlayerPointerExitHideDelaySeconds = 2", player_page_cs)
        self.assertIn("root.PointerExited += OnUserPointerExited", player_page_cs)
        self.assertIn("ScheduleChromeHide(PlayerPointerExitHideDelaySeconds)", player_page_cs)
        self.assertIn("AnimateChromeOpacity", player_page_cs)
        self.assertIn("Storyboard.SetTarget", player_page_cs)
        self.assertIn("DoubleAnimation", player_page_cs)
        state_changed_body = player_page_cs[
            player_page_cs.index("private void OnPlayerStateChanged") :
            player_page_cs.index("private void UpdatePlaybackLabels")
        ]
        self.assertNotIn("ShowChrome(true);", state_changed_body)
        self.assertNotIn("ScheduleChromeHide();", state_changed_body)
        toggle_play_pause_body = player_page_cs[
            player_page_cs.index("private async Task TogglePlayPauseAsync") :
            player_page_cs.index("private async Task SeekRelativeAsync")
        ]
        self.assertIn("ShowChrome(true);", toggle_play_pause_body)
        self.assertIn("ScheduleChromeHide();", toggle_play_pause_body)
        self.assertIn("PlayerVolume", player_page_cs)
        self.assertIn("PlayerVolumePanel", player_page_cs)
        self.assertIn("PlayerVolumeSlider", player_page_cs)
        self.assertIn("OnVolumeButtonClicked", player_page_cs)
        self.assertIn("CloseVolumePanel", player_page_cs)
        self.assertIn("FlyoutBase.SetAttachedFlyout(volumeButton, volumeFlyout)", player_page_cs)
        self.assertIn("FlyoutBase.ShowAttachedFlyout(_volumeButton)", player_page_cs)
        self.assertIn("OnUserPointerMoved", player_page_cs)
        self.assertIn("OnUserPointerPressed", player_page_cs)
        self.assertIn("CloseEpisodePanel", player_page_cs)
        self.assertIn("HideTransientPlayerChrome", player_page_cs)
        self.assertIn("CloseEpisodePanel(scheduleHide: false)", player_page_cs)
        self.assertIn("CloseVolumePanel(scheduleHide: false)", player_page_cs)
        self.assertIn("WhenNotPlaybackShortcut", player_page_cs)
        self.assertIn("HandlePlaybackShortcutAsync", player_page_cs)
        self.assertIn("_playbackShortcutClickGuard", player_page_cs)
        self.assertIn("_playbackShortcutKeyDown", player_page_cs)
        self.assertIn("UIElement.KeyDownEvent", player_page_cs)
        self.assertIn("UIElement.KeyUpEvent", player_page_cs)
        self.assertIn("handledEventsToo: true", player_page_cs)
        self.assertIn("Button button", player_page_cs)
        self.assertIn("button.AllowFocusOnInteraction = false", player_page_cs)
        self.assertNotIn("AddPlaybackKeyboardAccelerators", player_page_cs)
        self.assertNotIn("KeyboardAccelerator", player_page_cs)
        self.assertIn("VirtualKey.Space", player_page_cs)
        self.assertIn("TogglePlayPauseAsync", player_page_cs)
        self.assertIn('topToolbar.Children.Add(episodeButton)', player_page_cs)
        self.assertIn('bottomControls.Children.Add(subtitleButton)', player_page_cs)
        self.assertIn('bottomControls.Children.Add(audioButton)', player_page_cs)
        self.assertIn('bottomControls.Children.Add(fullScreenButton)', player_page_cs)
        self.assertNotIn('bottomControls.Children.Add(episodeButton)', player_page_cs)
        self.assertNotIn("PlayerSkipBack", player_page_cs)
        self.assertNotIn("PlayerSkipForward", player_page_cs)
        self.assertIn("SeekStepSeconds = 5", player_page_cs)
        self.assertIn("VirtualKey.Left", player_page_cs)
        self.assertIn("VirtualKey.Right", player_page_cs)
        self.assertIn("AttachPlaybackKeyHandler", player_page_cs)
        self.assertIn("OnPlayerControlKeyUp", player_page_cs)
        self.assertIn("IsPlayPauseKey", player_page_cs)
        self.assertIn("Failed to start native playback.", player_page_cs)
        self.assertIn("ShowPlaybackError", player_page_cs)
        self.assertIn("Failed to resume native playback position.", player_page_cs)
        self.assertIn("GoBackOrLibrary", shell_page_cs)
        self.assertIn("RemoveTopPlayerPagesFromBackStack", shell_page_cs)
        self.assertIn("_contentFrame.BackStack[lastIndex].SourcePageType != typeof(PlayerPage)", shell_page_cs)
        self.assertIn("_contentFrame.BackStack.RemoveAt(lastIndex)", shell_page_cs)
        self.assertIn("ShellPage.Current?.GoBackOrLibrary()", player_page_cs)
        self.assertNotIn("ShellPage.Current?.NavigateToMovie(_movieId)", player_page_cs)
        self.assertIn("_saveTimer.Tick += OnSaveTimerTick", player_page_cs)
        self.assertIn("Failed to save native playback progress.", player_page_cs)
        self.assertNotIn("_saveTimer.Tick += async (_, _) => await SaveProgressAsync(false)", player_page_cs)
        self.assertIn("ProtectedData", auth_service)
        self.assertIn("DataProtectionScope.CurrentUser", auth_service)
        self.assertIn("/auth/setup", api_client)
        self.assertIn("/media-roots", api_client)
        self.assertIn("/movies", api_client)
        self.assertIn("BuildEpisodeStillUrlAsync", api_client)
        self.assertIn("api/episode-still/{movieId}", api_client)
        self.assertIn("/progress/", api_client)
        self.assertIn("IsEpisode", movie_card_item)
        self.assertIn("HasEpisodeStill", movie_card_item)
        self.assertIn('E{Movie.TmdbEpisode.GetValueOrDefault():00}', movie_card_item)
        self.assertIn("EpisodeTitle", movie_card_item)
        self.assertIn("FallbackCoverUrl", movie_card_item)
        self.assertIn("CreateMovieCardItemAsync", browse_page_cs)
        self.assertIn("BuildEpisodeStillUrlAsync", browse_page_cs)
        self.assertIn("item.HasEpisodeStill ? 100 : 252", browse_page_cs)
        self.assertIn("triedFallback", browse_page_cs)
        self.assertIn("CreateMovieCardItemAsync(movie, \"folder\")", folder_page_cs)
        windows_csharp = "\n".join(
            path.read_text(encoding="utf-8")
            for path in (ROOT / "windows" / "MediaTree.Windows").rglob("*.cs")
        )
        self.assertNotIn("MpvExe", windows_csharp)
        self.assertNotIn("mpv.exe", windows_csharp)
        self.assertNotIn("MEDIATREE_WINDOWS_MPV_MODE", windows_csharp)
        self.assertNotIn("MEDIATREE_WINDOWS_MPV_MODE", mpv_native)
        self.assertNotIn('"force-window", "yes"', mpv_native)
        self.assertIn('"force-window", "no"', mpv_native)
        self.assertIn('"vo", "gpu-next"', mpv_native)
        self.assertIn("mpv_create", mpv_native)
        self.assertIn("mpv_initialize", mpv_native)
        self.assertIn("mpv_command", mpv_native)
        self.assertIn("mpv_get_property", mpv_native)
        self.assertIn("mpv_observe_property", mpv_native)
        self.assertIn("mpv_wait_event", mpv_native)
        self.assertIn("mpv_terminate_destroy", mpv_native)
        self.assertIn("mpv-2.dll", mpv_native)
        self.assertIn("_compositionWidth", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibMpvPlayerService.cs").read_text(encoding="utf-8"))
        self.assertIn("ApplyCompositionSize()", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibMpvPlayerService.cs").read_text(encoding="utf-8"))
        self.assertIn("SwapChainPanel", mpv_control)
        self.assertIn("SetSwapChain", mpv_control)
        self.assertIn(".As<ISwapChainPanelNative>()", mpv_control)
        self.assertIn("UpdateCompositionSize()", mpv_control)
        self.assertIn("_pendingSwapChain", mpv_control)
        self.assertIn("display-swapchain", mpv_control + mpv_native)
        self.assertIn("d3d11-output-mode=composition", mpv_native)
        self.assertIn("d3d11-composition-size", mpv_native)
        self.assertIn("NativeLibrary.Load(MpvDllPath)", mpv_native)
        self.assertIn("Task.Run(() => PipeToFileAsync", backend_service)
        self.assertNotIn("reader.EndOfStream", backend_service)

    def test_windows_native_ui_uses_responsive_fluent_layouts(self):
        fluent_theme = (ROOT / "windows" / "MediaTree.Windows" / "Styles" / "FluentTheme.cs").read_text(encoding="utf-8")
        main_window = (ROOT / "windows" / "MediaTree.Windows" / "MainWindow.xaml.cs").read_text(encoding="utf-8")
        shell_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "ShellPage.xaml.cs").read_text(encoding="utf-8")
        home_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "HomePage.xaml.cs").read_text(encoding="utf-8")
        login_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "LoginPage.xaml.cs").read_text(encoding="utf-8")
        setup_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "SetupPage.xaml.cs").read_text(encoding="utf-8")
        library_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "LibraryPage.xaml.cs").read_text(encoding="utf-8")
        browse_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "BrowsePage.xaml.cs").read_text(encoding="utf-8")
        favorites_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "FavoritesPage.xaml.cs").read_text(encoding="utf-8")
        folder_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "FolderPage.xaml.cs").read_text(encoding="utf-8")
        movie_detail_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "MovieDetailPage.xaml.cs").read_text(encoding="utf-8")
        settings_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "SettingsPage.xaml.cs").read_text(encoding="utf-8")
        player_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "PlayerPage.xaml.cs").read_text(encoding="utf-8")
        recent_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "RecentPage.xaml.cs").read_text(encoding="utf-8")

        self.assertIn("CompactBreakpoint = 760", fluent_theme)
        self.assertIn("MediumBreakpoint = 980", fluent_theme)
        self.assertIn("ControlCornerRadius => new(8)", fluent_theme)
        self.assertIn("CardCornerRadius => new(8)", fluent_theme)
        self.assertIn("MediaCornerRadius => new(8)", fluent_theme)
        self.assertIn("ApplyTextInput(TextBox", fluent_theme)
        self.assertIn("ApplyPasswordInput(PasswordBox", fluent_theme)
        self.assertIn("ApplyComboBox(ComboBox", fluent_theme)
        self.assertIn("ApplyNumberInput(NumberBox", fluent_theme)
        self.assertIn("ApplyCheckBox(CheckBox", fluent_theme)
        self.assertIn("ApplyListView(ListView", fluent_theme)
        self.assertIn("ApplyGridView(GridView", fluent_theme)
        self.assertIn("ApplySlider(Slider", fluent_theme)
        self.assertIn("ApplyFlyout(Flyout", fluent_theme)
        self.assertIn("ApplyContentDialog(ContentDialog", fluent_theme)
        self.assertNotIn("PreferenceRow(CheckBox", fluent_theme)
        self.assertIn("box.CornerRadius = ControlCornerRadius", fluent_theme)
        app_xaml = (ROOT / "windows" / "MediaTree.Windows" / "App.xaml").read_text(encoding="utf-8")
        self.assertIn('x:Key="ControlCornerRadius"', app_xaml)
        self.assertIn('x:Key="OverlayCornerRadius"', app_xaml)
        self.assertIn('x:Key="TextControlCornerRadius"', app_xaml)
        self.assertIn('x:Key="ComboBoxItemCornerRadius"', app_xaml)
        self.assertIn('x:Key="GridViewItemCheckBoxCornerRadius"', app_xaml)
        self.assertIn('x:Key="ListViewItemCheckBoxCornerRadius"', app_xaml)
        self.assertIn('<CornerRadius x:Key="ControlCornerRadius">8</CornerRadius>', app_xaml)
        self.assertIn('<CornerRadius x:Key="TextControlCornerRadius">8</CornerRadius>', app_xaml)
        self.assertIn('<Style TargetType="CheckBox" BasedOn="{StaticResource DefaultCheckBoxStyle}">', app_xaml)
        self.assertIn('<Setter Property="CornerRadius" Value="{StaticResource ControlCornerRadius}" />', app_xaml)
        self.assertIn('<Setter Property="MinHeight" Value="36" />', app_xaml)
        self.assertIn("PagePadding(double width)", fluent_theme)
        self.assertIn("SpaciousPagePadding(double width)", fluent_theme)

        self.assertIn("StartupStatusText", main_window)
        self.assertIn("StartupRetryButton", main_window)
        self.assertIn("StartupOpenLogs", main_window)
        self.assertIn("_isCompactNavigation", shell_page)
        self.assertIn("args.NewSize.Width < 900", shell_page)

        self.assertIn("root.SizeChanged", home_page)
        self.assertIn("FluentTheme.SpaciousPagePadding", home_page)
        self.assertIn("OnLoginFieldKeyDown", login_page)
        self.assertIn("VirtualKey.Enter", login_page)
        self.assertIn("LoginUsername", login_page)
        self.assertIn("ApplyScraperButtonsLayout", setup_page)
        self.assertIn("Focus(FocusState.Programmatic)", setup_page)

        self.assertIn("ApplyLibraryResponsiveLayout", library_page)
        self.assertIn("ApplyBrowseResponsiveLayout", browse_page)
        self.assertIn("ApplyFavoritesResponsiveLayout", favorites_page)
        self.assertIn("ApplyFolderResponsiveLayout", folder_page)
        self.assertIn("ApplyDetailResponsiveLayout", movie_detail_page)
        self.assertIn("ApplySettingsViewportLayout", settings_page)
        self.assertIn("HorizontalScrollMode = ScrollMode.Disabled", settings_page)
        self.assertIn("scrollViewer.SizeChanged", settings_page)
        self.assertIn("root.Width = Math.Max(0, viewportWidth)", settings_page)
        self.assertIn("SettingsColumnPreferredWidth = 400", settings_page)
        self.assertIn("SettingsColumnMinWidth = 340", settings_page)
        self.assertIn("SettingsColumnSpacing = 18", settings_page)
        self.assertIn("var settingsGrid = new Grid", settings_page)
        self.assertIn("settingsGrid.Width = gridWidth", settings_page)
        self.assertIn("CalculateSettingsColumnCount(contentWidth, _settingsCards.Count)", settings_page)
        self.assertIn("Math.Min(SettingsColumnPreferredWidth", settings_page)
        self.assertIn("settingsGrid.ColumnDefinitions.Clear()", settings_page)
        self.assertIn("RenderSettingsCardColumns(settingsGrid, columnCount, columnWidth)", settings_page)
        self.assertIn("Grid.SetColumn(columnStack, column)", settings_page)
        self.assertIn("columnStack.Children.Add(child)", settings_page)
        self.assertIn("SettingsHeaderCard", settings_page)
        self.assertIn("private static Border SectionCard", settings_page)
        self.assertIn("_settingsColumnWidth", settings_page)
        self.assertIn("ApplyLoadedLibraryRowWidths(columnWidth)", settings_page)
        self.assertIn("WrapText", settings_page)
        self.assertIn("ApplyLibrarySettingsRowLayout", settings_page)
        self.assertIn("ApplyScraperDescriptionLayout", settings_page)
        self.assertIn("Width = double.NaN", settings_page)
        self.assertIn("MaxWidth = double.PositiveInfinity", settings_page)
        self.assertIn("ApplyPlayerResponsiveLayout", player_page)
        self.assertIn("FluentTheme.ApplyListView(new ListView", browse_page)
        self.assertIn("FluentTheme.ApplyListView(new ListView", settings_page)
        self.assertIn("FluentTheme.ApplyGridView(new GridView", library_page)
        self.assertIn("FluentTheme.ApplyGridView(new GridView", browse_page)
        self.assertIn("FluentTheme.ApplyGridView(new GridView", player_page)
        self.assertIn("FluentTheme.ApplySlider(new Slider", player_page)
        self.assertIn("FluentTheme.ApplyFlyout(new Flyout", player_page)
        self.assertIn("FluentTheme.ApplyContentDialog(new ContentDialog", settings_page)

        self.assertIn("FluentTheme.MediaCornerRadius", browse_page)
        self.assertIn("FluentTheme.MediaCornerRadius", library_page)
        self.assertIn("FluentTheme.MediaCornerRadius", movie_detail_page)
        self.assertIn("FluentTheme.MediaCornerRadius", recent_page)
        self.assertIn("var mediaTree = AppServices.MediaTree", recent_page)
        self.assertIn("mediaTree.Library.GetMediaRootsAsync", recent_page)
        self.assertIn("mediaTree.Movie.GetRecentWatchedAsync", recent_page)
        self.assertIn("mediaTree.Api.BuildCoverUrlAsync", recent_page)
        self.assertNotIn("AppServices.Library", recent_page)
        self.assertNotIn("AppServices.Movie", recent_page)
        self.assertNotIn("AppServices.Api", recent_page)
        self.assertIn("FluentTheme.CardCornerRadius", settings_page)
        self.assertIn("SanitizeAutomationId", browse_page)
        self.assertIn("Replace(\":\", \"_\")", browse_page)
        self.assertIn("SanitizeAutomationId", library_page)
        self.assertIn("Replace(\":\", \"_\")", library_page)

    def test_windows_release_workflow_builds_only_when_full_update_required_or_manual(self):
        workflow = WINDOWS_WORKFLOW.read_text(encoding="utf-8")

        self.assertIn("requires_windows_base_update", workflow)
        self.assertIn("workflow_dispatch", workflow)
        self.assertIn("packaging/windows/build-windows.ps1", workflow)
        self.assertIn("steps.metadata.outputs.requires_windows_base_update == 'true'", workflow)
        self.assertIn("softprops/action-gh-release", workflow)
        self.assertIn('".zip"', workflow)


if __name__ == "__main__":
    unittest.main()
