import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
WINDOWS_PROJECT = ROOT / "windows" / "MediaTree.Windows" / "MediaTree.Windows.csproj"
WINDOWS_MANIFEST = ROOT / "windows" / "MediaTree.Windows" / "Package.appxmanifest"
WINDOWS_WORKFLOW = ROOT / ".github" / "workflows" / "windows-release.yml"
WINDOWS_BUILD_SCRIPT = ROOT / "packaging" / "windows" / "build-windows.ps1"
PYINSTALLER_SPEC = ROOT / "packaging" / "windows" / "mediatree-server.spec"


class WindowsPackagingTest(unittest.TestCase):
    def test_winui_project_bundles_backend_server_and_native_runtime(self):
        project = WINDOWS_PROJECT.read_text(encoding="utf-8")

        self.assertIn("<UseWinUI>true</UseWinUI>", project)
        self.assertIn("<WindowsPackageType>None</WindowsPackageType>", project)
        self.assertIn("<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>", project)
        self.assertIn("Microsoft.WindowsAppSDK", project)
        self.assertIn("CommunityToolkit.Mvvm", project)
        self.assertNotIn("Microsoft.Web.WebView2", project)
        self.assertIn("server\\**\\*", project)
        self.assertIn("mpv\\**\\*", project)
        self.assertIn("Package.appxmanifest", project)
        self.assertIn("<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>", project)

    def test_msix_manifest_declares_full_trust_desktop_app(self):
        manifest = WINDOWS_MANIFEST.read_text(encoding="utf-8")

        self.assertIn('Name="ZASENJC.MediaTree"', manifest)
        self.assertIn('Name="Windows.Desktop"', manifest)
        self.assertIn('Name="runFullTrust"', manifest)
        self.assertIn('Square150x150Logo="Assets\\Square150x150Logo.png"', manifest)

    def test_pyinstaller_spec_preserves_base_app_for_hot_updates(self):
        spec = PYINSTALLER_SPEC.read_text(encoding="utf-8")

        self.assertIn('"backend" / "app"', spec)
        self.assertIn('"base/app"', spec)
        self.assertIn('"frontend" / "dist"', spec)
        self.assertIn('"base/frontend/dist"', spec)
        self.assertIn('"backend" / "app" / "windows_entry.py"', spec)
        self.assertIn('name="mediatree-server"', spec)
        self.assertIn("collect_submodules", spec)
        self.assertIn("SPECPATH", spec)
        self.assertNotIn("__file__", spec)
        self.assertNotIn("ROOT = Path.cwd()", spec)
        self.assertNotIn('"app.main"', spec)

    def test_windows_build_script_runs_validation_before_packaging(self):
        script = WINDOWS_BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertLess(
            script.index("python -m pip install -r backend/requirements.txt"),
            script.index('python -m unittest discover -s tests -p "test_*.py"'),
        )
        self.assertIn("function Invoke-Native", script)
        self.assertIn("$FilePath = [string]$args[0]", script)
        self.assertNotIn("ValueFromRemainingArguments", script)
        self.assertIn("throw \"$FilePath failed with exit code $LASTEXITCODE\"", script)
        self.assertIn('python -m unittest discover -s tests -p "test_*.py"', script)
        self.assertIn("python -m compileall -q backend/app", script)
        self.assertIn("npm.cmd run build", script)
        self.assertIn("pyinstaller --noconfirm", script)
        self.assertIn('$ServerDist = Join-Path $Root "dist/windows/server"', script)
        self.assertIn('$ServerWork = Join-Path $Root "build/windows/mediatree-server"', script)
        self.assertIn("Remove-Item $ServerSource -Recurse -Force", script)
        self.assertIn("Remove-Item $ServerWork -Recurse -Force", script)
        self.assertIn("$MpvArchiveUrl", script)
        self.assertIn("py7zr", script)
        self.assertIn("mpv.exe", script)
        self.assertIn("mpv-2.dll", script)
        self.assertIn("$MsixVersion", script)
        self.assertIn("docs/assets/logo.png", script)
        self.assertIn("$OriginalManifest", script)
        self.assertIn("function Resolve-WindowsKitTool", script)
        self.assertIn("function Resolve-7ZipTool", script)
        self.assertIn("function Resolve-MSBuild", script)
        self.assertIn("function New-ExpandedAppxManifest", script)
        self.assertIn("function New-AppInstallerFile", script)
        self.assertIn("function New-TestSigningCertificate", script)
        self.assertIn("7zr.exe", script)
        self.assertIn("$SevenZipUrl", script)
        self.assertIn("/t:Publish", script)
        self.assertIn("WindowsAppSDKSelfContained=true", script)
        self.assertIn("WindowsPackageType=None", script)
        self.assertIn("SelfContained=true", script)
        self.assertIn("PublishSingleFile=false", script)
        self.assertIn("makeappx.exe", script)
        self.assertIn("signtool.exe", script)
        self.assertIn("MediaTree-Windows-$Version.msix", script)
        self.assertIn("MediaTree-Windows-$Version.appinstaller", script)
        self.assertIn("MediaTree-Windows-$Version.cer", script)
        self.assertIn("MediaTree-Windows-$Version-portable.zip", script)
        self.assertIn('".zip"', script)
        self.assertIn('".cer"', script)
        self.assertIn("Windows.FullTrustApplication", script)
        self.assertIn("ProcessorArchitecture", script)
        self.assertIn("MSIX package was not generated", script)
        self.assertIn("App installer file was not generated", script)
        self.assertIn("Portable package was not generated", script)
        self.assertNotIn("GenerateAppxPackageOnBuild=true", script)

    def test_windows_shell_uses_native_pages_api_client_and_libmpv(self):
        api_client = (ROOT / "windows" / "MediaTree.Windows" / "Services" / "MediaTreeApiClient.cs").read_text(encoding="utf-8")
        auth_service = (ROOT / "windows" / "MediaTree.Windows" / "Services" / "AuthSessionService.cs").read_text(encoding="utf-8")
        backend_service = (ROOT / "windows" / "MediaTree.Windows" / "Services" / "BackendProcessService.cs").read_text(encoding="utf-8")
        mpv_native = (ROOT / "windows" / "MediaTree.Windows" / "Interop" / "MpvNative.cs").read_text(encoding="utf-8")
        mpv_control = (ROOT / "windows" / "MediaTree.Windows" / "Controls" / "MpvPlayerControl.xaml.cs").read_text(encoding="utf-8")
        app = (ROOT / "windows" / "MediaTree.Windows" / "App.xaml.cs").read_text(encoding="utf-8")
        main_window = (ROOT / "windows" / "MediaTree.Windows" / "MainWindow.xaml.cs").read_text(encoding="utf-8")
        main_window_xaml = (ROOT / "windows" / "MediaTree.Windows" / "MainWindow.xaml").read_text(encoding="utf-8")
        fluent_theme = (ROOT / "windows" / "MediaTree.Windows" / "Styles" / "FluentTheme.cs").read_text(encoding="utf-8")
        shell_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "ShellPage.xaml").read_text(encoding="utf-8")
        shell_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "ShellPage.xaml.cs").read_text(encoding="utf-8")
        setup_required_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "SetupRequiredPage.xaml.cs").read_text(encoding="utf-8")
        setup_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "SetupPage.xaml").read_text(encoding="utf-8")
        setup_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "SetupPage.xaml.cs").read_text(encoding="utf-8")
        library_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "LibraryPage.xaml").read_text(encoding="utf-8")
        library_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "LibraryPage.xaml.cs").read_text(encoding="utf-8")
        folder_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "FolderPage.xaml").read_text(encoding="utf-8")
        folder_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "FolderPage.xaml.cs").read_text(encoding="utf-8")
        folder_card_item = (ROOT / "windows" / "MediaTree.Windows" / "ViewModels" / "FolderCardItem.cs").read_text(encoding="utf-8")
        browse_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "BrowsePage.xaml.cs").read_text(encoding="utf-8")
        favorites_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "FavoritesPage.xaml.cs").read_text(encoding="utf-8")
        settings_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "SettingsPage.xaml.cs").read_text(encoding="utf-8")
        ui_preference_store = (ROOT / "windows" / "MediaTree.Windows" / "Services" / "UiPreferenceStore.cs").read_text(encoding="utf-8")
        movie_detail_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "MovieDetailPage.xaml.cs").read_text(encoding="utf-8")
        navigation_parameters = (ROOT / "windows" / "MediaTree.Windows" / "Models" / "NavigationParameters.cs").read_text(encoding="utf-8")
        movie_dtos = (ROOT / "windows" / "MediaTree.Windows" / "Models" / "MovieDtos.cs").read_text(encoding="utf-8")
        player_page = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "PlayerPage.xaml").read_text(encoding="utf-8")
        player_page_cs = (ROOT / "windows" / "MediaTree.Windows" / "Views" / "PlayerPage.xaml.cs").read_text(encoding="utf-8")

        self.assertNotIn("WebView2", main_window_xaml)
        self.assertNotIn("Microsoft.Web.WebView2", main_window)
        self.assertNotIn("CoreWebView2", main_window)
        self.assertNotIn("AddScriptToExecuteOnDocumentCreatedAsync", main_window)
        self.assertIn("AuthSessionService", main_window)
        self.assertIn("MediaTreeApiClient", main_window)
        self.assertIn("ShellPage", main_window)
        self.assertIn("args.Handled = true", app)
        self.assertIn("ShowAndBringToFront()", main_window)
        self.assertIn("WindowNative.GetWindowHandle(this)", main_window)
        self.assertIn("ShowStartupFailure", main_window)
        self.assertIn("CenteredCard(stack", main_window)
        self.assertIn('AutomationProperties.SetAutomationId(startupTitle, "StartupTitle")', main_window)
        self.assertIn("HorizontalAlignment.Stretch", main_window)
        self.assertIn("MaxWidth = 480", main_window)
        self.assertIn("CenteredCard", fluent_theme)
        self.assertIn("HorizontalAlignment = HorizontalAlignment.Center", fluent_theme)
        self.assertIn("VerticalAlignment = VerticalAlignment.Center", fluent_theme)
        self.assertIn("ShellNavigation", shell_page + shell_page_cs)
        self.assertIn("ContentFrame", shell_page + shell_page_cs)
        self.assertIn("AutomationProperties.AutomationId", shell_page + shell_page_cs)
        self.assertIn("NavHome", shell_page + shell_page_cs)
        self.assertIn("NavBrowse", shell_page + shell_page_cs)
        self.assertIn("NavFavorites", shell_page + shell_page_cs)
        self.assertNotIn("NavLibrary", shell_page_cs)
        self.assertNotIn("NavRecent", shell_page_cs)
        self.assertNotIn('CreateNavigationButton("媒体库"', shell_page_cs)
        self.assertNotIn('CreateNavigationButton("最近观看"', shell_page_cs)
        self.assertIn("SetupRequiredPage", shell_page_cs)
        self.assertIn("SetupRequiredAddFolder", setup_required_page)
        self.assertIn("FolderPicker", setup_page_cs)
        self.assertIn("InitializeWithWindow.Initialize(picker", setup_page_cs)
        self.assertIn("Folder picker failed.", setup_page_cs)
        self.assertIn("AddLibraryAsync", setup_page + setup_page_cs)
        self.assertIn("SetupScraperTmdbMovie", setup_page_cs)
        self.assertIn("SetupScraperTmdbTv", setup_page_cs)
        self.assertIn("SetupScraperJavdatabase", setup_page_cs)
        self.assertIn("SetupTmdbAccessToken", setup_page_cs)
        self.assertIn("SetupLibraryPassword", setup_page_cs)
        self.assertNotIn('"tmdb", "SetupScraperTmdb"', setup_page_cs)
        self.assertIn("SaveTmdbConfigAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("NormalizeScraper", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("MoviesGrid", library_page + library_page_cs)
        self.assertIn("Failed to load native library movies.", library_page_cs)
        self.assertIn("Failed to start native library scan.", library_page_cs)
        self.assertIn("_suppressLibrarySelectionChanged", library_page_cs)
        self.assertIn("_movieLoadGeneration", library_page_cs)
        self.assertIn("CreateLibraryItem", library_page_cs)
        self.assertIn("Tag = root", library_page_cs)
        self.assertIn("Failed to change native library selection.", library_page_cs)
        self.assertIn("/folders", api_client)
        self.assertIn("FolderGrid", library_page_cs)
        self.assertIn("CreateFolderCard", library_page_cs)
        self.assertIn("FolderCardItem", library_page_cs)
        self.assertIn("UiPreferenceStore.Load", library_page_cs)
        self.assertIn("_hideHomeTitleText", library_page_cs)
        self.assertIn("_showSourceName", library_page_cs)
        self.assertIn("item.SourceName", library_page_cs)
        self.assertIn("SourceName => Folder.Name", folder_card_item)
        self.assertIn("FolderNavigationParameter", navigation_parameters)
        self.assertIn("NavigateToFolder", shell_page_cs)
        self.assertIn("_contentFrame.Navigate(typeof(FolderPage), new FolderNavigationParameter", shell_page_cs)
        self.assertIn("NavigateToPlayer(movieId);", shell_page_cs)
        self.assertNotIn("MovieDetailPage), new MovieNavigationParameter", shell_page_cs)
        self.assertIn("ShellPage.Current?.NavigateToFolder(item.Path, _activeMediaRoot, item.Title)", library_page_cs)
        self.assertNotIn("LoadMoviesAsync(item.Path)", library_page_cs)
        self.assertIn("FolderPage", folder_page + folder_page_cs)
        self.assertIn("FolderSeasonTabs", folder_page_cs)
        self.assertIn("FolderMoviesGrid", folder_page_cs)
        self.assertIn("GetMoviesAsync(_mediaRoot, _folderPath", folder_page_cs)
        self.assertIn("BuildSeasonTabs", folder_page_cs)
        self.assertIn("IsInSeason", folder_page_cs)
        self.assertIn("folder_levels", movie_dtos)
        self.assertIn("tmdb_season", movie_dtos)
        self.assertIn("tmdb_episode", movie_dtos)
        self.assertIn("episode_number", movie_dtos)
        self.assertIn("episode_title", movie_dtos)
        self.assertIn("LibraryLoadingText", library_page_cs)
        self.assertIn("SetLoading", library_page_cs)
        self.assertNotIn("ProgressRing", library_page_cs)
        self.assertIn("LibraryScanInfoText", library_page_cs)
        self.assertNotIn("new InfoBar", library_page_cs)
        self.assertIn("BrowsePage", shell_page_cs)
        self.assertIn("BrowseFoldersList", browse_page_cs)
        self.assertIn("BrowseMoviesGrid", browse_page_cs)
        self.assertIn("BrowseSearchBox", browse_page_cs)
        self.assertIn("BrowseSort", browse_page_cs)
        self.assertIn("GetMoviesAsync(_activeMediaRoot, _activeFolderPath", browse_page_cs)
        self.assertIn("FavoritesPage", shell_page_cs)
        self.assertIn("FavoritesMoviesGrid", favorites_page_cs)
        self.assertIn("FavoritesSort", favorites_page_cs)
        self.assertIn("GetFavoritesAsync", favorites_page_cs)
        self.assertIn("RemoveTagAsync", favorites_page_cs)
        self.assertIn("SettingsUpdateStatusText", settings_page_cs)
        self.assertIn("ShowUpdateStatus", settings_page_cs)
        self.assertIn("Failed to check native Windows updates.", settings_page_cs)
        self.assertIn("SettingsUiPrefsCard", settings_page_cs)
        self.assertIn("SettingsAuthCard", settings_page_cs)
        self.assertIn("SettingsLibraryCard", settings_page_cs)
        self.assertIn("SettingsScraperCard", settings_page_cs)
        self.assertIn("SettingsBackupCard", settings_page_cs)
        self.assertIn("SettingsUpdateCard", settings_page_cs)
        self.assertIn("SettingsSaveGlobal", settings_page_cs)
        self.assertIn("SettingsHideHomeTitleText", settings_page_cs)
        self.assertIn("SettingsShowSourceName", settings_page_cs)
        self.assertIn("OnUiPreferenceChanged", settings_page_cs)
        self.assertIn("UiPreferenceStore.Save", settings_page_cs)
        self.assertIn("hideHomeTitleText", ui_preference_store)
        self.assertIn("showSourceName", ui_preference_store)
        self.assertIn("SettingsTmdbApiKey", settings_page_cs)
        self.assertIn("SettingsChangePassword", settings_page_cs)
        self.assertIn("SettingsBackupCore", settings_page_cs)
        self.assertIn("SettingsBackupFull", settings_page_cs)
        self.assertIn("SettingsRestoreBackup", settings_page_cs)
        self.assertIn("SettingsLibrarySettingsList", settings_page_cs)
        self.assertIn("SettingsLibraryStatusText", settings_page_cs)
        self.assertIn("SettingsTmdbAccessToken", settings_page_cs)
        self.assertNotIn("SettingsSaveTmdbToken", settings_page_cs)
        self.assertIn("SettingsTmdbTokenStatusText", settings_page_cs)
        self.assertIn("LoadTmdbConfigAsync", settings_page_cs)
        self.assertIn("SaveGlobalConfigAsync", settings_page_cs)
        self.assertIn("SettingsSaveLibrary_", settings_page_cs)
        self.assertIn("SettingsLibraryScraper_", settings_page_cs)
        self.assertIn("正在保存刮削器设置并重新扫描", settings_page_cs)
        self.assertIn("ScraperOptions", settings_page_cs)
        self.assertIn('new("tmdb_movie", "TMDB 电影", "适合电影库；tmdbid 调用 /movie 精确刮削", true)', settings_page_cs)
        self.assertIn('new("tmdb_tv", "TMDB 剧集/番剧", "适合剧集、番剧、电视剧库；tmdbid 调用 /tv 精确刮削", true)', settings_page_cs)
        self.assertIn('new("bangumi", "Bangumi", "适合番剧、动画、二次元条目，数据可能不全", false)', settings_page_cs)
        self.assertIn('new("javdatabase", "Javdatabase", "适合 JAV 番号识别和刮削", false)', settings_page_cs)
        self.assertIn('new("auto", "自动", "自动判断刮削源，但可能效果不好", true)', settings_page_cs)
        self.assertIn('new("none", "不刮削", "只扫描本地文件，不联网刮削元数据", false)', settings_page_cs)
        self.assertNotIn("new InfoBar", settings_page_cs)
        self.assertIn("GetLibrarySettingsAsync", api_client)
        self.assertIn('GetAsync<List<LibrarySettingDto>>("/library-settings"', api_client)
        self.assertIn("SaveLibrarySettingAsync", api_client)
        self.assertIn("SaveTmdbConfigAsync", api_client)
        self.assertIn("SaveGlobalConfigAsync", api_client)
        self.assertIn("ChangePasswordAsync", api_client)
        self.assertIn("GetFavoritesAsync", api_client)
        self.assertIn("RemoveTagAsync", api_client)
        self.assertIn("ClearLibraryAsync", api_client)
        self.assertIn("RestoreBackupAsync", api_client)
        self.assertIn("tmdb_access_token", api_client)
        self.assertIn("tmdb_api_key", api_client)
        self.assertIn("TmdbAccessToken", (ROOT / "windows" / "MediaTree.Windows" / "Models" / "LibraryDtos.cs").read_text(encoding="utf-8"))
        self.assertIn("GetLibrarySettingsAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("SaveLibrarySettingAsync", (ROOT / "windows" / "MediaTree.Windows" / "Services" / "LibraryService.cs").read_text(encoding="utf-8"))
        self.assertIn("Failed to load native movie detail.", movie_detail_page_cs)
        self.assertIn("DetailStatusText", movie_detail_page_cs)
        self.assertIn("ImageFailed", movie_detail_page_cs)
        self.assertIn("ShowDetailError", movie_detail_page_cs)
        self.assertNotIn("ProgressBar", movie_detail_page_cs)
        self.assertIn("PlayerHost", player_page + player_page_cs)
        self.assertIn("PlayerStatusText", player_page_cs)
        self.assertIn("Failed to start native playback.", player_page_cs)
        self.assertIn("ShowPlaybackError", player_page_cs)
        self.assertIn("GoBackOrLibrary", shell_page_cs)
        self.assertIn("RemoveTopPlayerPagesFromBackStack", shell_page_cs)
        self.assertIn("_contentFrame.BackStack[lastIndex].SourcePageType != typeof(PlayerPage)", shell_page_cs)
        self.assertIn("_contentFrame.BackStack.RemoveAt(lastIndex)", shell_page_cs)
        self.assertIn("ShellPage.Current?.GoBackOrLibrary()", player_page_cs)
        self.assertNotIn("ShellPage.Current?.NavigateToMovie(_movieId)", player_page_cs)
        self.assertIn("_saveTimer.Tick += OnSaveTimerTick", player_page_cs)
        self.assertIn("Failed to save native playback progress.", player_page_cs)
        self.assertNotIn("_saveTimer.Tick += async (_, _) => await SaveProgressAsync(false)", player_page_cs)
        self.assertIn("ProtectedData", auth_service)
        self.assertIn("DataProtectionScope.CurrentUser", auth_service)
        self.assertIn("/auth/setup", api_client)
        self.assertIn("/media-roots", api_client)
        self.assertIn("/movies", api_client)
        self.assertIn("/progress/", api_client)
        self.assertIn("mpv_create", mpv_native)
        self.assertIn("mpv_initialize", mpv_native)
        self.assertIn("mpv_command", mpv_native)
        self.assertIn("mpv_get_property", mpv_native)
        self.assertIn("mpv_observe_property", mpv_native)
        self.assertIn("mpv_wait_event", mpv_native)
        self.assertIn("mpv_terminate_destroy", mpv_native)
        self.assertIn("mpv-2.dll", mpv_native)
        self.assertIn("SwapChainPanel", mpv_control)
        self.assertIn("SetSwapChain", mpv_control)
        self.assertIn("display-swapchain", mpv_control + mpv_native)
        self.assertIn("d3d11-output-mode=composition", mpv_native)
        self.assertIn("d3d11-composition-size", mpv_native)
        self.assertIn("MEDIATREE_WINDOWS_MPV_MODE", mpv_native)
        self.assertIn("Task.Run(() => PipeToFileAsync", backend_service)
        self.assertNotIn("reader.EndOfStream", backend_service)

    def test_windows_release_workflow_builds_only_when_base_update_required_or_manual(self):
        workflow = WINDOWS_WORKFLOW.read_text(encoding="utf-8")

        self.assertIn("requires_windows_base_update", workflow)
        self.assertIn("workflow_dispatch", workflow)
        self.assertIn("packaging/windows/build-windows.ps1", workflow)
        self.assertIn("steps.metadata.outputs.requires_windows_base_update == 'true'", workflow)
        self.assertIn("softprops/action-gh-release", workflow)
        self.assertIn('".zip"', workflow)


if __name__ == "__main__":
    unittest.main()
